# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_message_message_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='value',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='message_state',
            field=models.BooleanField(default=False),
        ),
    ]
