# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_auto_20170603_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name1', to=settings.AUTH_USER_MODEL)),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Message')),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='message_state',
        ),
        migrations.AddField(
            model_name='state',
            name='message_list',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
