# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20170604_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='message_list',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
