# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_state_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='user_type',
            field=models.CharField(default='lightgreen', max_length=30),
        ),
    ]
