# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 18:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_post_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 18, 23, 18, 175769, tzinfo=utc)),
        ),
    ]
