# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20170605_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('c', 'Commented on'), ('p', 'Published'), ('e', 'Extended')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='user_since',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='state',
            name='user_type',
            field=models.CharField(choices=[('beginner', 'green'), ('intermediate', 'blue'), ('advanced', 'orange'), ('master', 'red')], default='beginner', max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='state',
            name='last_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Activity'),
        ),
    ]
