# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0020_auto_20170606_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('followers', models.IntegerField(default=0)),
                ('summary', models.CharField(max_length=2000)),
                ('topContributors', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='state',
            name='user_type',
            field=models.CharField(choices=[('beginner', 'black'), ('intermediate', 'purple'), ('advanced', 'orange'), ('master', 'red')], default='beginner', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='topics',
            field=models.ManyToManyField(default='Rules And Regulations', to='post.Topics'),
        ),
    ]
