# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20170718_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='topics',
        ),
        migrations.AddField(
            model_name='settings',
            name='First_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='Last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
