# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20170718_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Last_name',
        ),
        migrations.AddField(
            model_name='settings',
            name='topics',
            field=models.ManyToManyField(default='Rules And Regulations', to='post.Topics'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='summary',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
